#!/usr/bin/env sh

cp \
  ./node_modules/instantsearch.js/dist/instantsearch.js \
  ./playground/dist/instantsearch.js

cp \
  ./node_modules/instantsearch.js/dist/instantsearch.css \
  ./playground/dist/instantsearch.css

cp \
  ./node_modules/instantsearch.js/dist/instantsearch-theme-algolia.css \
  ./playground/dist/instantsearch-theme-algolia.css

cp \
  ./node_modules/fragments.css/dist/fragments.css \
  ./playground/dist/fragments.css
